- name: Find and delete files 
  hosts: all
  become: yes
  tasks:
    - name: find files and directories
      find:
        paths: /opt/sample
        file_type: any
      register: out

    - debug: msg={{out}}

    - name: Remove files and directories using file module
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{out.files}}"
