- name: Student Application Setup
  hosts: all
  become: yes
  vars:
    APPUSER: student
    APPUSERHOME: /home/{{APPUSER}}
    TOMCAT_URL: http://mirrors.wuchna.com/apachemirror/tomcat/tomcat-9/v9.0.13/bin/apache-tomcat-9.0.13.tar.gz
    TARFILE: "{{ TOMCAT_URL.split('/') | last }}"
    TOMCAT_LOC: "{{APPUSERHOME}}/{{TARFILE | regex_replace('.tar.gz','') }}"
    
  tasks:
    - name: Install Java
      package:
        name: java
        state: present

    - name: Add studentapp user 
      user:
        name: "{{APPUSER}}"

    - name: Download and extract tomcat
      unarchive:
        src: "{{TOMCAT_URL}}"
        dest: "{{APPUSERHOME}}"
        remote_src: yes
      become_user: "{{APPUSER}}"

    - name: Find files in webapps
      find: 
        paths: "{{TOMCAT_LOC}}/webapps"
        file_type: any
      register: out

    - name: Remove old webapps
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{out.files}}"
